THP_train:
  base_config:
    backend: torch
    base_dir: ./checkpoints/THP/retweet/20250729_172611
    dataset_id: retweet
    model_id: THP
    runner_id: std_tpp
    stage: train
  model_config:
    dropout: 0.0
    hidden_size: 16
    loss_integral_num_sample_per_step: 20
    num_heads: 4
    num_layers: 3
    thinning:
      dtime_max: 5
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 16
    use_ln: false
  trainer_config:
    batch_size: 64
    early_stopping_patience: 20
    gpu: 0
    learning_rate: 0.001
    max_epoch: 300
    metrics:
    - acc
    - rmse
    optimizer: adam
    save_freq: 10
    seed: 2019
    shuffle: false
    use_tfb: false
    valid_freq: 5
data:
  retweet:
    data_format: pkl
    data_specs:
      num_event_types: 3
      pad_token_id: 3
      padding_side: right
      truncation_side: right
    test_dir: data/retweet/retweet/test.pkl
    train_dir: data/retweet/retweet/train.pkl
    valid_dir: data/retweet/retweet/dev.pkl
pipeline_config_id: runner_config
