data_config:
  train_dir: data/taxi/taxi/train.pkl
  valid_dir: data/taxi/taxi/dev.pkl
  test_dir: data/taxi/taxi/test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 10
    pad_token_id: 10
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: train
  backend: torch
  dataset_id: taxi
  runner_id: std_tpp
  model_id: AttNHP
  base_dir: ./checkpoints/AttNHP/taxi/20250729_184500
  specs:
    log_folder: ./checkpoints/AttNHP/taxi/20250729_184500/1632575_140648979072064_250729-235141
    saved_model_dir: ./checkpoints/AttNHP/taxi/20250729_184500/1632575_140648979072064_250729-235141/models/saved_model
    saved_log_dir: ./checkpoints/AttNHP/taxi/20250729_184500/1632575_140648979072064_250729-235141/log
    output_config_dir: ./checkpoints/AttNHP/taxi/20250729_184500/1632575_140648979072064_250729-235141/AttNHP_train_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 16
  time_emb_size: 16
  num_layers: 3
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
  num_event_types_pad: 11
  num_event_types: 10
  event_pad_index: 10
  model_id: AttNHP
  pretrained_model_dir: null
  gpu: 0
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: 0
  batch_size: 4
  max_epoch: 300
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 5
  use_tfb: false
  metrics:
  - acc
  - rmse
